# Generated by Django 5.2.7 on 2025-11-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rango', models.CharField(choices=[('admin', 'admin'), ('moderador', 'moderador'), ('normal', 'normal')], max_length=20)),
                ('rol', models.CharField(choices=[('supervisor', 'supervisor'), ('tutor', 'tutor'), ('estudiante', 'estudiante')], max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
