# Generated by Django 5.2.8 on 2025-12-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naruapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rango',
            field=models.CharField(choices=[('admin', 'admin'), ('moderador', 'moderador'), ('normal', 'normal')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('supervisor', 'supervisor'), ('tutor', 'tutor'), ('estudiante', 'estudiante')], default='estudiante', max_length=20),
        ),
    ]
