# Generated by Django 5.2.7 on 2025-12-02 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naruapp', '0002_alter_usuario_rango_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminViewModel_CuentaIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'View Ingreso',
                'verbose_name_plural': 'View Ingreso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminViewModel_CuentaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'View Registro',
                'verbose_name_plural': 'View Registro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminViewModel_NaruClases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'View Clases',
                'verbose_name_plural': 'View Clases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminViewModel_NaruEntradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'View Entradas',
                'verbose_name_plural': 'View Entradas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('resumen', models.TextField(max_length=250)),
                ('contenido', models.TextField()),
                ('categoria', models.CharField(choices=[('estudio', 'estudio'), ('fisica', 'fisica'), ('matematicas', 'matematicas'), ('ingles', 'ingles')])),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='naruapp.usuario')),
            ],
        ),
    ]
